# Generated by Django 4.2.5 on 2023-09-23 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='access_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductAccess',
        ),
    ]
